const userObjectId = "";

export const MI_ROPERO = [
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "buzo-horse",
    type: 14,
    composition: {
      cotton: 100,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "tumbleDryLow",
      "iron1",
      "noDryClean",
    ],
    label: "",
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "camiseta-titular-river-plate-24-25",
    type: 14,
    composition:{
      polyester: 100
    },
    wash: [
      "noBleachAllowed",
      "noDryClean",
      "washTemperature1",
      "noTumbleDry",
      "iron1",
      "removePromptly",
      "similarColors",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "buzo-canguro-hombre-fila-hoodie-essential",
    type: 14,
    composition: {
      cotton: 86,
      polyester: 14,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "noTumbleDry",
      "noDryClean",
      "noIron",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "lunar-tee",
    type: 14,
    composition: {
      cotton: 100,
    },
    wash: ["washTemperature1"],
    extra: ["washAndIronBackwards"],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "nike-pant-jean-white",
    type: 14,
    sizes: {
      total_large: 104,
      botamaga: 23.5,
      waist: 46,
      rise: 30,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "tumbleDryLow",
      "iron2",
      "noDryClean",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "tampa-bay-tee",
    composition: {
      cotton: 100,
    },
    type: 14,
    wash: [
      "washTemperature1",
      "similarColors",
      "bleachAllowed",
      "tumbleDryLow",
      "noIron",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "elt-jacket",
    type: 14,
    composition: {
      cotton: 45,
      polyester: 55,
      liningPolyester: 100,
    },
    sizes: {
      total_large: 69,
      total_width: 61,
    },
    wash: [
      "handWash",
      "washTemperature1",
      "iron1",
      "noBleachAllowed",
      "noDryClean",
    ],
    label: "",
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "n-tee",
    type: 14,
    composition: {
      cotton: 100,
    },
    wash: ["washTemperature1", "noBleachAllowed", "tumbleDryLow"],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "bolivia",
    type: 14,
    composition: {
      cotton: 100,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "noTumbleDry",
      "iron1",
      "noDryClean",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "sastrero",
    type: 14,
    sizes: {
      total_large: 102,
    },
    composition: {
      polyester: 65,
      viscose: 35,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "iron1",
      "noDryClean",
      "waterRunOff",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "puffer-nike-korea",
    description: "buyed at @tianguis.store. instagram.com/p/C8ibI15Me6o/. ",
    type: 14,
    sizes: {
      total_width: 56,
      total_large: 68,
      sleeves: 58,
    },
    composition: {
      nylon: 100,
      liningPolyester: 100,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "noIron",
      "noDryClean",
      "tumbleDryNormal",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "tommy-jacket",
    description: "buyed at @sotano.vtg",
    type: 14,
    composition: {
      polyester: 100,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "tumbleDryLow",
      "iron1",
      "noDryClean",
      "similarColors",
      "removePromptly",
    ],
    extras: ["closeZippers"],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "salomon-polo",
    description: "made in tailand",
    type: 14,
    composition: {
      polyester: 100,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "tumbleDryLow",
      "iron1",
      "noDryClean",
      "similarColors",
    ],
    extras: ["washInsideOut"],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "green-polo-tonix",
    description: "buyed at @tianguis.store. made in vietnam",
    type: 14,
    composition: {
      polyester: 100,
    },
    wash: [
      "washTemperature1",
      "removePromptly",
      "noBleachAllowed",
      "tumbleDryLow",
      "noIron",
    ],
    extras: ["washInsideOut"],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "cream-jean",
    type: 14,
    composition: {
      denim: 100,
      cotton: 100,
    },
    wash: ["washTemperature1", "noBleachAllowed", "iron2", "tumbleHang"],
    extras: ["washInsideOut"],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "taverniti-buzo",
    type: 14,
    composition: {
      cotton: 90,
      polyester: 10,
    },
    wash: [
      "handWash",
      "washTemperature1",
      "noBleachAllowed",
      "iron2",
      "tumbleHang",
      "perchloroethylene",
    ],
    extras: ["washInsideOut"],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    description: "buyed at @caju.clothess instagram.com/p/C3qzHGcJZcB",
    slug: "buzo-and1",
    type: 14,
    composition: {
      cotton: 80,
      polyester: 20,
    },
    wash: [
      "washTemperature1",
      "tumbleDryLow",
      "noBleachAllowed",
      "iron1",
      "similarColors",
      "removePromptly",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "umbro-pant",
    type: 14,
    sizes: {
      total_large: 94,
      waist: 44,
      rise: 30,
      botamaga: 20,
    },
    wash: ["washTemperature1", "bleachAllowed", "iron1"],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "musculosa-nike",
    type: 14,
    composition: {
      polyester: 100,
    },
    sizes: {
      total_width: 52,
      total_large: 70,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "tumbleDryLow",
      "iron1",
      "noDryClean",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "campera-green",
    type: 14,
    composition: {
      cotton: 100,
      liningPolyester: 100,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "noTumbleDry",
      "iron1",
      "tumbleHang",
      "perchloroethylene",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "vest-yd",
    type: 14,
    composition: {
      nylon: 100,
      liningPolyester: 100,
    },
    wash: [
      "washTemperature1",
      "iron2",
      "noTumbleDry",
      "perchloroethylene",
      "noBleachAllowed",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "buzo-printify",
    type: 14,
    composition: {
      cotton: 50,
      polyester: 50,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "tumbleDryLow",
      "noIron",
      "noDryClean",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    description:
      "buyed at @bigsizeesport/@diggingclubb. instagram.com/p/DAUWV-NxziK",
    slug: "nike-nocta",
    type: 11,
    composition: {
      lining: 79,
      polyester: 21,
    },
    wash: [
      "handWash",
      "noBleachAllowed",
      "dryInPosition",
      "noIron",
      "noDryClean",
    ],
  },
  {
    userId: userObjectId,
    thumbnail: "",
    slug: "afa-98",
    type: 14,
    composition: {
      polyamide: 62,
      polyester: 48,
    },
    wash: [
      "washTemperature1",
      "noBleachAllowed",
      "iron1",
      "perchloroethylene",
      "waterRunOff",
    ],
  },
];
